#
# web-based InterCOM - platform for collaborative design
# docker production use:
# Example docker-compose using jwilder/nginx-proxy & jrcs/letsencrypt-nginx-proxy-companion
#

version: '3'
services:
  icweb-db:
    container_name: icweb-db
    image: postgres:12
    volumes:
      - ./db:/var/lib/postgresql/data
    restart: always
    env_file:
      - ./.env

  icweb-app:
    container_name: icweb-app
    build: .
    restart: always
    ports:
      - "3030:3000"
    volumes:
      - ./files:/files
    env_file:
      - ./.env
