#
# web-based InterCOM - platform for collaborative design
# docker example for full local dev env.
#

version: '3'
services:
  dev-intercom-db:
    container_name: dev-intercom-db
    image: postgres:12
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - ./apps/backend/.env

  dev-intercom-backend:
    container_name: dev-intercom-backend
    build:
      context: .
      dockerfile: ./apps/backend/builds/Dockerfile
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./apps/backend:/app/apps/backend  # Mount the local backend directory to the container
      - /app/apps/backend/node_modules  # Use an anonymous volume for node_modules to avoid host contamination
      - ./files:/files  # Mount any additional directories as needed
    env_file:
      - ./apps/backend/.env

  dev-intercom-frontend:
    container_name: dev-intercom-frontend
    build:
        context: .
        dockerfile: ./apps/frontend/Dockerfile-dev
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./apps/frontend:/app/apps/frontend  # Mount the local frontend directory to the container
      - /app/apps/frontend/node_modules  # Use an anonymous volume for node_modules to avoid host contamination
    env_file:
      - ./apps/backend/.env
