# Use a specific version of node to ensure consistency across environments
FROM node:18-slim

# Install pnpm globally
RUN npm install -g pnpm

# Create app directory
WORKDIR /app

# Copy package.json and pnpm-lock.yaml files (or package-lock.json if not using pnpm)
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./

# Install dependencies using pnpm


COPY apps/frontend ./apps/frontend

WORKDIR /app/apps/frontend

EXPOSE 8080

RUN pnpm install --shamefully-hoist

# Serve the static files with `serve`
# The `serve` command should point to the build directory where your static files are located after the build

CMD ["pnpm", "run", "dev"]
#CMD ["tail", "-f", "/dev/null"]
