#
# web-based InterCOM - platform for collaborative design
# docker production use:
# Example docker-compose using jwilder/nginx-proxy & jrcs/letsencrypt-nginx-proxy-companion
#

version: '3'
services:
  icweb-db:
    container_name: icweb-db
    image: postgres:12
    volumes:
      - ./db:/var/lib/postgresql/data
    restart: always
    env_file:
      - secrets.env
  icweb-app:
    container_name: icweb-app
    image: thk-code-arch/intercom:latest
    restart: always
    environment:
      - VIRTUAL_HOST=
      - LETSENCRYPT_HOST=
      - LETSENCRYPT_EMAIL=
    volumes:
      - files:/files
    env_file:
      - secrets.env

networks:
  default:
    external:
      name: jwilder-proxy

volumes:
  files:
