name: Publish Docker Image

on:
  push:
    branches:
      - '*'
  release:
    types: [published, edited]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push (main branch)
        if: github.ref == 'refs/heads/main'
        id: docker_build_main
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: thkcodearch/intercom:latest

      - name: Build and push (non-main branches)
        if: github.ref != 'refs/heads/main' && contains(github.ref, 'refs/heads/')
        id: docker_build_dev
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: thkcodearch/intercom-dev:latest

      - name: Image digest (main)
        if: steps.docker_build_main.outputs.digest != ''
        run: echo ${{ steps.docker_build_main.outputs.digest }}

      - name: Image digest (non-main)
        if: steps.docker_build_dev.outputs.digest != ''
        run: echo ${{ steps.docker_build_dev.outputs.digest }}
